# Use an official Ubuntu 22.04 LTS (Jammy) linux parent image
FROM ubuntu:22.04

RUN <<EOM
# Update and install packages
apt-get update
apt-get install -y openssh-server libpam-tacplus
rm -rf /var/lib/apt/lists/*

# Create privilege seperation directory
mkdir -p /run/sshd

# Add test user
addgroup test
adduser -D -G test test
EOM

# Update sshd_config
# Update pam.d/ssh

# Expose the port the app runs on
EXPOSE 2222

# Run the ssh server
ENTRYPOINT ["/usr/sbin/sshd", "-p", "2222", "-D", "-e"]
